import puppeteer from 'puppeteer-core';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const BASE = process.argv[2] || 'https://imunco.github.io/sense-of-immersion';
const O = resolve(dirname(fileURLToPath(import.meta.url)), 'shots');
const b = await puppeteer.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true, args: ['--no-sandbox','--disable-gpu','--hide-scrollbars'] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 });
await p.goto(BASE + '/', { waitUntil: 'networkidle2', timeout: 90000 });
await p.evaluate(() => document.fonts.ready).catch(() => {});
await wait(3500);
await p.screenshot({ path: O + '/F1-live-hero.png' });
await p.evaluate(() => { location.hash = '#/web'; });
await wait(2200);
await p.screenshot({ path: O + '/F2-live-web-empty.png' });
await p.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
await p.goto(BASE + '/', { waitUntil: 'networkidle2' });
await wait(2600);
await p.screenshot({ path: O + '/F3-live-mobile.png' });
await b.close();
console.log('final live shots done');
