import puppeteer from 'puppeteer-core';
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const BASE = 'https://imunco.github.io/sense-of-immersion';
const b = await puppeteer.launch({ executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true, args: ['--no-sandbox','--disable-gpu'] });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 1000 });
await p.goto(BASE + '/', { waitUntil: 'networkidle2', timeout: 90000 });
await p.waitForFunction(() => !!window.__yixian, { timeout: 40000 }).catch(() => {});
await wait(1000);
await p.evaluate(() => { location.hash = '#/cast'; });
await wait(400);
await p.type('#name-input', '持久化测试', { delay: 12 });
await p.click('#to-wish');
await wait(600);
await p.type('#wish-input', '这条用来验证：什么都不做，它也会自己归档。', { delay: 8 });
await wait(2600);
await p.click('#submit-wish');
await p.waitForFunction(() => location.hash === '#/reveal', { timeout: 90000 });
await wait(1500);
console.log('ID=' + await p.evaluate(() => window.__yixian.last.id));
await b.close();
